FROM node:14.16.0-buster-slim

ARG APP_PATH=/__w/tabletopbuddy/tabletopbuddy

WORKDIR ${APP_PATH}
COPY ["package.json", "${APP_PATH}"]

RUN npm install
ENV PATH ${APP_PATH}/node_modules/.bin:$PATH

EXPOSE 3000

COPY . ${APP_PATH}

