FROM node:14.16.0-buster-slim

RUN apt-get update && apt-get install sudo git -y
RUN usermod -aG sudo node

COPY --chown=node ["package.json", "./"]

RUN npm install
ENV PATH $GITHUB_WORKSPACE/node_modules/.bin:$PATH

EXPOSE 3000

COPY . ./

CMD ["npm", "start"]
