FROM node:14.16.0-buster-slim

ARG APP_PATH=/home/node/app

RUN mkdir -p ${APP_PATH}
COPY ["package.json", "${APP_PATH}"]

RUN npm install
ENV PATH ${APP_PATH}/node_modules/.bin:$PATH

EXPOSE 3000

COPY . ./

ENTRYPOINT [ "${APP_PATH}/entrypoint.sh" ]
