version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - /home/node/app/frontend/node_modules
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/home/worker/app
