# Generated by Django 3.1.5 on 2021-02-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='name',
        ),
    ]
