# Generated by Django 3.1.5 on 2021-02-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210206_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(related_name='players', to='server.Player'),
        ),
    ]
