# Generated by Django 3.1.5 on 2021-02-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210215_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='game_sessions',
            field=models.ManyToManyField(related_name='players', to='server.GameSession'),
        ),
    ]
