# Generated by Django 3.1.5 on 2021-02-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20210215_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_sessions',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(related_name='game_sessions', to='server.Player'),
        ),
    ]
