name: Tabletop Buddy CI - backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Tests
      run: |
        coverage run --source='.' -m pytest
    - name: Coverage
      run: |
        coverage report -m > coverage_report
        cat coverage_report
    - name: Get coverage percentage
      run: |
        echo "COVERAGE_PERCENTAGE=$(awk 'NF>1{print $NF}' coverage_report | tail -1)" >> $GITHUB_ENV
    - name: Create python coverage badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 552ce237f255723acc32075d96d8d709
        filename: python-coverage-badge.json
        label: Python coverage
        message: ${{ env.COVERAGE_PERCENTAGE }}
        labelColor: blue
    
