name: Tabletop Buddy CI - backend

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'frontend/**'
    - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'frontend/**'
    - '.github/workflows/frontend.yml'

defaults:
  run:
    working-directory: backend

jobs:
  tests:

    runs-on: ubuntu-latest
    container:
      image: python:3-slim-buster

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Tests
      run: |
        coverage run --source='.' -m pytest
    - name: Coverage
      run: |
        coverage report -m > coverage_report
        cat coverage_report
    - name: Get coverage percentage
      run: |
        echo "COVERAGE_PERCENTAGE=$(tail -1 coverage_report | awk '{print $NF}')" >> $GITHUB_ENV
    - name: Create python coverage badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 552ce237f255723acc32075d96d8d709
        filename: python-coverage-badge.json
        label: Python coverage
        message: ${{ env.COVERAGE_PERCENTAGE }}
        labelColor: blue
    
