# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tabletop Buddy CI - frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash
    working-directory: tabletopbuddy_frontend


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }} 
    - run: npm ci
    - run: npm run coverage -- --coverageReporters='text-summary' > javascript_coverage_report
    - run: echo "COVERAGE_PERCENTAGE=$(awk '{print $3}' javascript_coverage_report | tail -2)" >> $GITHUB_ENV
    - name: Create javascript coverage badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 552ce237f255723acc32075d96d8d709
        filename: coverage-badge.json
        label: Javascript line coverage
        message: ${{ env.COVERAGE_PERCENTAGE }}
        color: green
