name: Frontend

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'backend/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'backend/**'

jobs:
  blax:
    runs:
      using: 'docker'
      image: 'frontend/Dockerfile.ci'
      entrypoint: frontend/entrypoint.sh
    steps:
      - name: echo whatever
        run: echo "whatever"

  build:
    runs-on: ubuntu-latest
    container: docker:dind
    needs: blax
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Print github workspace
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "github.ref = ${{ github.ref }}"
          echo "GITHUB_CONTEXT = $GITHUB_CONTEXT"
          echo "APP_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.ci
          push: true
          tags: jinlisek/tabletopbuddy:latest
          build-args: APP_PATH=${{ env.APP_PATH }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  tests:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: jinlisek/tabletopbuddy:latest

    steps:
    - name: Print github workspace
      run: |
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        echo "github.workspace = ${{ github.workspace }}"
        echo "github.ref = ${{ github.ref }}"
        echo "GITHUB_CONTEXT = $GITHUB_CONTEXT"
    - name: Run tests
      run: npm run test
    - name: Run coverage
      run: npm run coverage-ci
    - name: Generate coverage badge
      run: |
        npm run coverage-summary > cov_report
        echo "COV_PERCENTAGE=$(cat cov_report | tail -7 | head -1 | awk '{print $3}')" >> $GITHUB_ENV
    - name: Create javascript coverage badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 552ce237f255723acc32075d96d8d709
        filename: javascript-coverage-badge.json
        label: Javascript line coverage
        message: ${{ env.COVERAGE_PERCENTAGE }}
        labelColor: yellow
