# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tabletop Buddy CI - frontend

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'backend/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'backend/**'

defaults:
  run:
    shell: bash
    working-directory: frontend


jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Build frontend image
      run: docker-compose build frontend
    - name: Run tests
      run: docker-compose run frontend npm run test
    - name: Run coverage
      run: docker-compose run frontend npm run coverage-ci
    - name: Generate coverage badge
      run: docker-compose run frontend npm run coverage-summary > cov_report
      run: echo "COV_PERCENTAGE=$(cat cov_report | tail -7 | head -1 | awk '{print $3}')" >> $GITHUB_ENV
    - name: Create javascript coverage badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 552ce237f255723acc32075d96d8d709
        filename: javascript-coverage-badge.json
        label: Javascript line coverage
        message: ${{ env.COVERAGE_PERCENTAGE }}
        labelColor: yellow
