# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tabletop Buddy CI - frontend

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'backend/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'backend/**'

defaults:
  run:
    shell: bash
    working-directory: frontend


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jinlisek/tabletopbuddy:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build frontend image
      run: docker-compose build frontend
    - name: Run tests
      run: docker-compose run frontend npm run test
    - name: Run coverage
      run: docker-compose run frontend npm run coverage-ci
    - name: Generate coverage badge
      run: |
        docker-compose run frontend npm run coverage-summary > cov_report
        echo "COV_PERCENTAGE=$(cat cov_report | tail -7 | head -1 | awk '{print $3}')" >> $GITHUB_ENV
    - name: Create javascript coverage badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 552ce237f255723acc32075d96d8d709
        filename: javascript-coverage-badge.json
        label: Javascript line coverage
        message: ${{ env.COVERAGE_PERCENTAGE }}
        labelColor: yellow
