name: Frontend

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'backend/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'backend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: node:14.16.0-buster-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Generate coverage badge
        run: |
          npm run coverage-summary > cov_report
          echo "COVERAGE_PERCENTAGE=$(cat cov_report | tail -2 | head -1 | awk '{print $3}')" >> $GITHUB_ENV
      - name: Create javascript coverage badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 552ce237f255723acc32075d96d8d709
          filename: javascript-coverage-badge.json
          label: Javascript line coverage
          message: ${{ env.COVERAGE_PERCENTAGE }}
          labelColor: yellow
